name: bacterial_genome_pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.12.0
  - snakemake=9.13.7
  - snakemake-executor-plugin-slurm=1.4.0
  - snakemake-executor-plugin-slurm-jobstep=0.3.0
  - fastp=1.0.1
  - filtlong=0.3.1
  - autocycler=0.5.2
  - raven-assembler=1.8.3       # https://github.com/lbcb-sci/raven
  - canu=2.3                    # https://github.com/marbl/canu
  - flye=2.9.6                  # https://github.com/mikolmogorov/Flye
  - metamdbg=1.2               # https://github.com/GaetanBenoitDev/metaMDBG
  - miniasm=0.3                 # https://github.com/lh3/miniasm
  - necat=0.0.1_update20200803  # https://github.com/xiaochuanle/NECAT
  - plassembler=1.8.1          # https://github.com/gbouras13/plassembler
  - nextdenovo=2.5.2            # https://github.com/Nextomics/NextDenovo
  - bwa-mem2=2.3
  - polypolish=0.6.1
  - minipolish>=0.2.0            # https://github.com/rrwick/Minipolish
  - sra-tools>=3.2.1
  - coincbc>=2.10.13
  - nextpolish>=1.4.1            # https://github.com/Nextomics/NextPolish
  - minimap2>=2.28               # https://github.com/lh3/minimap2
  - minipolish>=0.2.0            # https://github.com/rrwick/Minipolish
  - nextpolish>=1.4.1            # https://github.com/Nextomics/NextPolish
  - racon>=1.5.0                 # https://github.com/lbcb-sci/racon
