# Input/output
samples_dir: samples/hybrid_assembly
reads_dir: raw_sequencing_reads
results_dir: results

# Default threads per job
threads: 16

# Per-rule resources
fastp:
  threads: 8
  mem_gb: 2
  runtime: 7200

filtlong:
  threads: 1
  mem_gb: 4
  runtime: 7200

autocycler:
  threads: 16
  mem_gb: 2
  runtime: 172800

polypolish:
  threads: 16
  mem_gb: 1
  runtime: 21600

assembly_stats:
  threads: 2
  mem_gb: 2
  runtime: 3600

