# Input/output
samples_dir: samples/hybrid_assembly
reads_dir: raw_sequencing_reads
results_dir: results

# Default threads per job
threads: 16

# Per-rule resources
fastp:
  threads: 4
  mem_gb: 4
  runtime: 120

filtlong:
  threads: 1
  mem_gb: 8
  runtime: 120

autocycler:
  threads: 16
  mem_gb: 32
  runtime: 2880

polypolish:
  threads: 16
  mem_gb: 16
  runtime: 360

assembly_stats:
  threads: 2
  mem_gb: 4
  runtime: 60

